config/routes.rb
Rails.application.routes.draw do
  get 'users/edit'
  root :to => 'home#index'
  resources :users
  resources :workouts
  resources :exercises
  get 'complete_workout', to: 'workout_session#complete_workout'
  get 'workout_session', to: 'workout_session#index'
  get 'dashboard', to: 'dashboard#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :exercise_records
  
  after_update :create_record

  enum weight_metric: [:feet, :cm]
  enum time_metric: [:seconds, :minutes]

  def create_record
    check_changes = ["weight", "reps", "sets", "time"]
    value_changed = ""
    check_changes.map { |value| previous_changes[value] && value_changed = value}

    return unless value_changed.present?

    ExerciseRecord.create(exercise_id: id, name: value_changed, before: previous_changes[value_changed][0], after: previous_changes[value_changed][1])
  end
end

app/models/exercise_record.rb
class ExerciseRecord < ApplicationRecord
  belongs_to :exercise
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :workouts
  has_many :exercises, through: :workouts
  has_many :exercise_records, through: :exercises
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :exercises

  after_create :set_user_workout_stage
  before_destroy :remove_user_workout_stage

  def set_user_workout_stage
     return if user.workout_stage.present?

     user.workout_stage = rank
     user.save!
  end

  def remove_user_workout_stage
    return unless user.workout_stage === rank
    user.workouts.size > 0 && user.workout_stage = user.workouts.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:update, :destroy]
  def index

  end

  def new
    @exercise = Exercise.new
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to edit_workout_path(@exercise.workout_id), notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: edit_workout_path(@exercise.workout_id) }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to request.referrer, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: request.referrer }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exercise.destroy
    redirect_to request.referrer
  end

private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :reps, :weight, :sets, :time, :workout_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     @user = User.find_by(email: params[:email])
     if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to '/welcome'
     else
        redirect_to '/login'
     end
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to welcome_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: welcome_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login

  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user || User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :height, :height_metric, :weight, :weight_metric)
  end
end

app/controllers/workout_session_controller.rb
class WorkoutSessionController < ApplicationController
  before_action :set_workout_session

  def complete_workout
    user = @workout.user

    return unless user.workouts.size > 1

    if user.workouts.where(rank: @workout.rank + 1).any?
      user.workout_stage = @workout.rank + 1
    else
      user.workout_stage = user.workouts.order(rank: :asc).first.rank
    end

    user.save

    redirect_to dashboard_path
  end
private

  def set_workout_session
    @workout = current_user.workouts.where(rank: current_user.workout_stage).first
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:update]

  def index
    @workouts = current_user.workouts
  end

  def new
    @workout = Workout.new
  end

  def edit
    @workout = Workout.find(params[:id])
    @exercise = Exercise.new
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_path, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: workouts_path }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workouts_path, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: workouts_path }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def set_workout
    @workout = Workout.find(params[:id])
  end
  def workout_params
    params.require(:workout).permit(:name, :rank)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workout_session_helper.rb
module WorkoutSessionHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/dashboard/index.html.erb
<div class="dashboard-wrapper">
  <div class="content-container">
    <% if current_user.workouts.any? && current_user.workout_stage %>
      <%= link_to "Start Workout", workout_session_path, class: "btn-start" %>
    <% else %>
      <h1><center>Add Workouts to begin</center></h1>
    <% end %>
    <hr/>
    <div class="activity-logs">
      <h1>Activity Logs</h1>

      <% current_user.exercise_records.order('created_at DESC').each do |record| %>
      <div class="log">
        <p><em><%= record.created_at.strftime("%B %d, %Y - %H:%M") %></em></p>
        <p><%= record.exercise.name %> <%= record.name %> updated from <%= record.before %> to <%= record.after %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/_form.html.erb
<%= form_with model: @exercise do |f| %>
  <h1>New Exercise</h1>

  <div class="field">
    <%= f.label "Exercise Name" %><br/>
    <%= f.text_field :name, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label "Repetitions" %><br/>
    <%= f.number_field :reps, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label "Sets" %><br/>
    <%= f.number_field :sets, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label "Weight" %><br/>
    <%= f.text_field :weight, class: "text-input" %>
  </div>

  <%= f.hidden_field :workout_id, value: workout_id %>

  <%= f.submit "Save", class: "button" %>
<% end %>

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/new.html.erb
<h1>Exercises#new</h1>
<p>Find me in app/views/exercises/new.html.erb</p>

app/views/home/index.html.erb
<div class="content-container">
  <h1>Home Page</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= render "menu/dashboard_navbar" %>
    <% else %>
      <%= render "menu/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/menu/_dashboard_navbar.html.erb
<nav class="navbar">
  <ul class="main-navbar content-container">
    <li class="left"><%= link_to "Home", dashboard_path %></li>
    <li class="left"><%= link_to "My Workouts", workouts_path %></li>
    <li class="left"><%= link_to "Progress", workouts_path %></li>
    <li class="left"><%= link_to "Profile", users_edit_path %></li>
    <li class="right"><%= link_to "Sign Out", "#" %></li>
  </ul>
</nav>

app/views/menu/_navbar.html.erb
<nav class="navbar">
  <ul class="main-navbar content-container">
    <li class="left"><%= link_to "Home", root_path %></li>
    <li class="left"><%= link_to "Features", "#" %></li>
    <li class="left"><%= link_to "Pricing", "#" %></li>
    <li class="right"><%= link_to "Sign In", login_path %></li>
  </ul>
</nav>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <div class="field">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email, class: "text-input" %>
  </div>

  <%= f.submit "Save" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="content-container">
  <h1>Editing Profile</h1>
  <%= render "form" %>
</div>

app/views/users/new.html.erb
<div class="content-container">
  <h1>Sign Up</h1>
  <%= render "form" %>
</div>

app/views/users/show.html.erb
<h1>SHow</h1>

app/views/workout_session/index.html.erb
<div class="content-container">
  <h1>You are on <%= @workout.name %></h1>

  <table class="workout-session">
    <thead>
      <tr>
        <td>Exercise</td>
        <td>Weight</td>
        <td>Time</td>
        <td>Done?</td>
        <td>Update</td>
      </tr>
    </thead>
    <tbody>
    <% @workout.exercises.each do |exercise| %>
      <%= form_with model: exercise do |f| %>
        <tr>
          <td><%= exercise.name %></td>
          <td><%= f.text_field :weight %></td>
          <td><%= f.text_field :time %></td>
          <td><input type="checkbox"></td>
          <td><%= f.submit "Save" %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

  <%= link_to "Complete Workout", complete_workout_path, class: "btn-start" %>
</div>

app/views/workouts/_form.html.erb
<%= form_with model: @workout do |f| %>
  <div class="field">
    <%= f.label "Workout Name" %><br/>
    <%= f.text_field :name, class: "text-input" %>
  </div>
  <div class="field">
    <%= f.label "Workout Order" %><br/>
    <%= f.number_field :rank, class: "text-input" %>
  </div>
  <br/>
  <%= f.submit 'Save Workout', :class => "button" %>
<% end %>

app/views/workouts/_modal.html.erb
<div class="modal" id="modal">
  <div class="modal-content">
     <span class="close">&times;</span>
     <%= render "exercises/form", workout_id: @workout.id %>
   </div>
</div>

<script>
  $('.close').click(function(){
    $('#modal').css('display', 'none');
  })
</script>

app/views/workouts/edit.html.erb
<div class="content-container">
    <h1>
      Editing <%= @workout.name %>
      <i class="fa fa-trash float-right" aria-hidden="true"></i>
    </h1>
    <%= render "form" %>
    <%= render "modal" %>
    <div class="exercise-list">
      <h1><%= @workout.name %> Exercises <button id="modalButton" class="float-right">New <i class="fa fa-plus" aria-hidden="true"></i></button></h1>
      <table class="table">
        <thead>
          <tr>
            <td>Exercise</td>
            <td>Reps</td>
            <td>Sets</td>
            <td>Weight</td>
            <td>Time</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody>
        <% if @workout.exercises.size > 0 %>
          <% @workout.exercises.each do |exercise| %>
            <%= form_with model: exercise do |f| %>
            <tr>
              <td><%= f.text_field :name %></td>
              <td><%= f.text_field :reps %></td>
              <td><%= f.text_field :sets %></td>
              <td><%= f.text_field :weight %></td>
              <td><%= f.text_field :time %></td>
              <td class="table__actions">
                <%= f.button do %>
                  <i class="fa fa-floppy-o" aria-hidden="true"></i>
                <% end %>
                <%= link_to exercise_path(exercise.id), method: :delete, data: { confirm: 'Are you sure you want to delete this?'} do %>
                  <i class="fa fa-trash" title="Delete"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
        <% end %>
        <% else %>
          <tr>
            <td colspan="6">No exercises have been added to this workout.</td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

<script>
  $(document).ready(function(){
    var modal = $('#modal');

    $('#modalButton').click(function(){
      modal.css('display', 'block');
    })

    $('#editModalButton').click(function(){
      modal.css('display', 'block');
    })
  })

</script>

app/views/workouts/index.html.erb
<div class="workout-wrapper">
  <div class="content-container">
    <span class="flex">
      <h1 class="">
        My Workouts
        <%= link_to "Create new workout", new_workout_path, class: "button float-right" %>
      </h1>

    <div class="workout-list">
    <% current_user.workouts.each do |workout| %>
      <strong><%= link_to workout.name, edit_workout_path(workout.id) %></strong>

      <ul>
        <% workout.exercises.each do |exercise| %>
        <li><%= exercise.name %></li>
        <% end %>
      </ul>
    <% end %>
    </div>

  </div>
</div>

app/views/workouts/new.html.erb
<div class="content-container">
  <h1>New Workout</h1>
  <%= render "form" %>
</div>